name: DoubleJump
version: 1.5.2
main: com.doublejump.bluenatural.DoubleJump
author: BlueNatural
website: ko-fi.com/bluenatural
softdepend: [TitleBarAPI]

commands:
  doublejump:
    description: show all commands of DoubleJump
    usage: /<command>
    aliases: dj
    
permissions:
  dj.byass:
    description: If has this perm player who can not double jump
  dj.help:
    description: If has this perm player who can show all commands of DoubleJump
  dj.prevent:
    description: If has this perm player who can prevent player can double jump
  dj.reload:
    description: If has this perm player who can reload plugin
